backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "source/assets/images"
public_folder: "assets/images"

collections:
  - name: 'Pages'
    label: 'Pages'
    delete: false
    files:
      - file: "source/_pages/home.md"
        label: "Home"
        name: "home"
        fields:
          - {label: 'Title', name: 'title', widget: 'hidden', default: ''}
          - {label: 'Permalink', name: 'permalink', widget: 'hidden', default: 'index.html'}
          - {label: 'Extends', name: 'extends', widget: 'hidden', default: '_layouts.home'}
          - {label: 'Page Description', name: 'description', widget: 'text'}
          - {label: 'Slider Caption', name: 'slide_caption', widget: 'string'}
          - {label: 'Slider Sub Caption', name: 'slide_sub_caption', widget: 'string'}
          - {label: 'Mission Statement', name: 'mission_statement', widget: 'text'}

      - file: "source/_pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: 'Title', name: 'title', widget: 'hidden'}
          - {label: 'Extends', name: 'extends', widget: 'hidden'}
          - {label: 'Permalink', name: 'permalink', widget: 'hidden'}
          - {label: 'Section', name: 'section', widget: 'hidden'}
          - label: 'Meta'
            name: 'meta'
            widget: 'object'
            feilds:
              - {label: 'Page Description', name: 'page_description', widget: 'string'}
          - {label: 'Body', name: 'body', widget: 'markdown'}

  - name: 'about'
    label: 'About'
    delete: false
    files:
      - file: 'source/_about/about.md'
        lable: 'About'
        name: 'about'
        fields:
          - {label: 'Title', name: 'title', widget: 'hidden'}
          - {label: 'Extends', name: 'extends', widget: 'hidden'}
          - {label: 'Permalink', name: 'permalink', widget: 'hidden'}
          - {label: 'Section', name: 'section', widget: 'hidden'}
          - {label: 'Body', name: 'body', widget: 'markdown'}

  - name: "services"
    label: "Services"
    folder: "source/_services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "extends", widget: "hidden", default: "_layouts.service"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sequence", name: "sequence", required: false, widget: "number", default: "0"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Post Img", name: "post_img", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
