backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "source/assets/images"
public_folder: "assets/images"

collections:
  - name: "services"
    label: "Service"
    folder: "source/_services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "extends", widget: "hidden", default: "_layouts.service"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sequence", name: "sequence", required: false, widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Post Img", name: "post_img", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'Home'
    label: 'Home Page'
    folder: 'source/_home'
    fields:
      - {label: "Title", name: "title", widget: "hidden", default: ""}
      - {label: "Permalink", name:"permalink", widget: "hidden", default: "index.html" }
      - {labe: "Extends", name: "extends", widget: "hidden", default: "_layouts.home" }
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Slide Caption", name: "slide_caption", widget: "string"}
      - {label: "Slide Sub Caption", name: "slide_sub_caption", widget: "string"}
      - {label: "Mission Statement", name: "mission_statement", widget: "text"}
      - label: "Slides"
        name: "slides"
        widget: "list"
        optional: true
        field:
          - { label: "Slide", widget: "image", optional: false }
