backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "/assets/images"
public_foler: "source/assets/images"

collections:
  - name: "services"
    label: "Service"
    folder: "source/_services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "extends", widget: "hidden", default: "_layouts.service"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sequence", name: "sequence", required: false, widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Post Img", name: "post_img", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
