backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "source/assets/images"
public_folder: "assets/images"

collections:
  - name: 'Pages'
    label: 'Pages'
    delete: false
    files:
      - file: "source/_pages/home.md"
        label: "Home"
        name: "home"
        fields:
          - {label: 'Title', name: 'title', widget: 'hidden', default: ''}
          - {label: 'Permalink', name: 'permalink', widget: 'hidden', default: 'index.html'}
          - {label: 'Extends', name: 'extends', widget: 'hidden', default: '_layouts.home'}
          - {label: 'Page Description', name: 'description', widget: 'text'}
          - label: Slides
            name: slides
            widget: list
            required: false
            fields:
              - {label: 'Slide', name: 'img', widget: 'image'}
              - {label: 'Alt', name: 'alt', widget: 'string'}
          - {label: 'Slider Caption', name: 'slide_caption', widget: 'string'}
          - {label: 'Slider Sub Caption', name: 'slide_sub_caption', widget: 'string'}
          - {label: 'Mission Statement', name: 'mission_statement', widget: 'text'}

      - file: "source/_pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: 'Title', name: 'title', widget: 'hidden'}
          - {label: 'Extends', name: 'extends', widget: 'hidden'}
          - {label: 'Permalink', name: 'permalink', widget: 'hidden'}
          - {label: 'Section', name: 'section', widget: 'hidden'}
          - label: Slides
            name: slides
            widget: list
            required: false
            fields:
              - {label: 'Slide', name: 'img', widget: 'image'}
              - {label: 'Alt', name: 'alt', widget: 'string'}
          - {label: 'Body', name: 'body', widget: 'markdown'}

      - file: "source/_pages/service.md"
        label: "Service"
        name: 'service'
        fields:
          - {label: 'Permalink', name: 'permalink', widget: 'hidden'}
          - {label: 'Extends', name: 'extends', widget: 'hidden'}
          - label: Slides
            name: slides
            widget: list
            required: false
            fields:
              - {label: 'Slide', name: 'img', widget: 'image'}
              - {label: 'Alt', name: 'alt', widget: 'string'}
          - {label: 'Description', name: 'description', widget: 'text'}
          - {label: 'Title', name: 'title', widget: 'hidden'}

      - file: "source/_pages/contact.md"
        label: "Contact"
        name: 'contact'
        fields:
          - {label: 'Permalink', name: 'permalink', widget: 'hidden'}
          - {label: 'Extends', name: 'extends', widget: 'hidden'}
          - {label: 'Title', name: 'title', widget: 'hidden'}
          - label: Slides
            name: slides
            widget: list
            required: false
            fields:
              - {label: 'Slide', name: 'img', widget: 'image'}
              - {label: 'Alt', name: 'alt', widget: 'string'}
          - {label: 'Description', name: 'description', widget: 'text'}
          - {label: 'Section', name: 'section', widget: 'hidden'}
          - {label: 'Body', name: 'body', widget: 'markdown'}

  - name: "services"
    label: "Services"
    folder: "source/_services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "extends", widget: "hidden", default: "_layouts.service"}
      - label: Slides
        name: slides
        widget: list
        required: false
        fields:
          - {label: 'Slide', name: 'img', widget: 'image'}
          - {label: 'Alt', name: 'alt', widget: 'string'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sequence", name: "sequence", required: false, widget: "number", default: "0"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Post Img", name: "post_img", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: 'jobs'
    label: 'Jobs'
    folder: "source/_latest_jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: 'Extends', name: 'extends', widget: 'hidden', default: '_layouts.latest-job'}
      - label: Slides
        name: slides
        widget: list
        required: false
        fields:
          - {label: 'Slide', name: 'img', widget: 'image'}
          - {label: 'Alt', name: 'alt', widget: 'string'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Date', name: 'date', widget: 'date', format: "MM DD YY"}
      - {label: 'Before and After Picture', name: 'before_after_pic', widget: 'image'}
      - {label: 'Before and After Alternative Text', name: 'before_after_pic_desc', widget: 'string'}
      - {label: 'Page Description', name: 'description', widget: 'text'}
      - {label: 'Section', name: 'section', widget: 'hidden', default: 'content'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
